opsi_wiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'), 
    path('page/', include('pages.urls')),
    path('user/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('partners/', include('partners.urls')),
    path('process/', include('processmap.urls')),
    path('library/', include('fileslibrary.urls')),
    path('image-map-creator/', include('imagemap.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('programmer/', views.programmer_pages_list, name='programmer_pages_list'),
    path('constructor/', views.constructor_pages_list, name='constructor_pages_list'),
    path('project_manager/', views.project_manager_pages_list, name='project_manager_pages_list'),
    path('circuit_engineer/', views.circuit_engineer_pages_list, name='circuit_engineer_pages_list'),
    path('detail/<int:id>', views.page_detail, name='detail'),
    path('new/', views.update_page, name='create_page'),
    path('update/<int:id>', views.update_page, name='update_page'),
    path('delete/<int:id>', views.delete_page, name='delete_page'),
]

partners/urls.py
from django.urls import path
from partners import views

app_name = 'partners'

urlpatterns = [
    path('', views.partners_list, name='partners_list'),
    path('contractor/detail/<int:id>', views.contractor_detail, name='contractor_detail'),
    path('contractor/add/', views.update_contractor, name='add_contractor'),
    path('contractor/update/<int:id>', views.update_contractor, name='update_contractor'),
    path('contractor/delete/<int:id>', views.delete_contractor, name='delete_contractor'),

    path('supplier/detail/<int:id>', views.supplier_detail, name='supplier_detail'),
    path('supplier/add/', views.update_supplier, name='add_supplier'),
    path('supplier/update/<int:id>', views.update_supplier, name='update_supplier'),
    path('supplier/delete/<int:id>', views.delete_supplier, name='delete_supplier'),

    path('company/comments/add/', views.leave_comment, name='leave_comment'),
    path('company/comments/delete/<int:id>', views.delete_comment, name='delete_comment'),
]

pages/models.py
from django.db import models
from django.urls import reverse
import os
from ckeditor.fields import RichTextField 


class Category (models.Model):
    SOFTWARE_DEVELOPMENT = 'SOFT_DEV'
    CONSTRUCTION = 'CONSTRUCT'
    PROJECT_MANAGMENT = 'PROJ_MANAG'
    CIRCUIT_ENGINEERING = 'CIRC_ENG'
    PROCESS_SYSTEM_INTEGRATION = 'PROC_SI'

    CATEGORY_CHOICES = [
        (None, '---------'),
        (SOFTWARE_DEVELOPMENT, 'Программирование'),
        (CONSTRUCTION, 'Конструирование'),
        (PROJECT_MANAGMENT, 'Управление проектами'),
        (CIRCUIT_ENGINEERING, 'Схемотехника'),
        (PROCESS_SYSTEM_INTEGRATION, 'Процесс "Системная интеграция"'),
    ]

    name = models.CharField(max_length=20, choices=CATEGORY_CHOICES,
            verbose_name='Название', unique=True )
    order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)

    def __str__ (self):
        return self.get_name_display()

    class Meta():
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def get_url(self):
        return Category.get_url_by_name(self.name)

    def get_url_by_name(name):
        urls = {
            Category.SOFTWARE_DEVELOPMENT : reverse('pages:programmer_pages_list'),
            Category.CONSTRUCTION : reverse('pages:constructor_pages_list'),
            Category.PROJECT_MANAGMENT : reverse('pages:project_manager_pages_list'),
            Category.CIRCUIT_ENGINEERING : reverse('pages:circuit_engineer_pages_list'),
            Category.PROCESS_SYSTEM_INTEGRATION : reverse('processmap:process'),
        }
        return urls.get(name, reverse('home'))


class Topic (models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)
    description = models.TextField(verbose_name='Описание', blank=True)
    order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)

    def __str__ (self):
        return self.name

    class Meta():
        verbose_name = "Тема"
        verbose_name_plural = "Темы"


class Page(models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, verbose_name='Тема', on_delete=models.CASCADE) 
    short_description = RichTextField(verbose_name='Краткое описание', blank=True)

    def __str__(self):
        return str(self.category) + ': ' + self.name

    class Meta():
        verbose_name = "Страница"
        verbose_name_plural = "Страницы"


class Section(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    headline = models.CharField(verbose_name='Оглавление', max_length=200, blank=True)
    content = RichTextField(verbose_name='Раздел', blank=True)

    def __str__(self):
        return self.headline

    class Meta():
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"

def file_storage_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/uploads/files_<page.id>/<filename>
    return 'uploads/files_{0}/{1}'.format(instance.page.id, filename)

class File(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    upload = models.FileField(verbose_name='Файл', upload_to=file_storage_path, max_length=500)
    alter_name = models.CharField(verbose_name='Переименовать файл', max_length=200, blank=True)
    comment = models.CharField(verbose_name='Комментарий', max_length=200, blank=True)

    def filename(self):
        if self.alter_name:
            return self.alter_name
        else:
            return os.path.basename(self.upload.name).replace('_', ' ')

    def __str__(self):
        return self.filename()

    class Meta():
        verbose_name = "Файл"
        verbose_name_plural = "Файлы"

class Link(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя', max_length=200, blank=True)
    link = models.TextField(verbose_name='Ссылка')

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "Внешняя ссылка"
        verbose_name_plural = "Внешние ссылки"

class Reference(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя', max_length=200)
    link = models.TextField(verbose_name='Ссылка', blank=True)
    author = models.CharField(verbose_name='Автор', max_length=200, blank=True)
    pub_date = models.CharField(verbose_name='Дата публикации', max_length=200, blank=True)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "Литература"
        verbose_name_plural = "Литература"

partners/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from PIL import Image


class Comment(models.Model):
	author = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
	text = models.TextField(verbose_name='Текст комментария')
	pub_date = models.DateTimeField(auto_now=True, verbose_name='Дата публикации')

	content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
	object_id = models.PositiveIntegerField()
	content_object = GenericForeignKey('content_type', 'object_id')

	def object_name(self):
		if self.content_object:
			return str(self.content_object)
		else:
			return "Object has been deleted or doesn't exist"

	def __str__(self):
		return self.author.username + ': ' + 'comment...'

	class Meta():
		verbose_name = 'Отзыв'
		verbose_name_plural = 'Отзывы'


class Contractor(models.Model):
	company_name = models.CharField(max_length=200, verbose_name='Наименование организации')
	icon = models.ImageField(default='pertner_icon_default.png', upload_to='partners_icons', verbose_name='Иконка' )
	contacts = models.TextField(verbose_name='Контакты')
	service = models.TextField(verbose_name='Тип услуги, деятельность')
	examples = models.TextField(verbose_name='Примеры работ', blank = True)
	rating = models.PositiveSmallIntegerField(verbose_name='Оценка', default=0, 
		validators=[
			MaxValueValidator(5),
			MinValueValidator(0)
		] )
	comments = GenericRelation(Comment, related_query_name='comments')

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		icon = Image.open(self.icon.path)
		if icon.height > 300 or icon.width > 300:
			output_size = (300, 300)
			icon.thumbnail(output_size)
			icon.save(self.icon.path)

	def class_name(self):
		return self.__class__.__name__

	def __str__(self):
		return self.company_name

	class Meta:
		verbose_name = 'Субподрядчик'
		verbose_name_plural = 'Субподрядчики'



class Supplier(models.Model):
	company_name = models.CharField(max_length = 200, verbose_name = 'Наименование организации')
	icon = models.ImageField(default='pertner_icon_default.png', upload_to='partners_icons', verbose_name = 'Иконка')
	contacts = models.TextField(verbose_name='Контакты')
	service = models.TextField(verbose_name='Тип поставляемого оборудования')
	rating = models.PositiveSmallIntegerField(verbose_name='Оценка', default=0, 
		validators=[
			MaxValueValidator(5),
			MinValueValidator(0)
		] )	
	comments = GenericRelation(Comment, related_query_name='comments')

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		icon = Image.open(self.icon.path)
		if icon.height > 300 or icon.width > 300:
			output_size = (300, 300)
			icon.thumbnail(output_size)
			icon.save(self.icon.path)

	def class_name(self):
		return self.__class__.__name__

	def __str__(self):
		return self.company_name

	class Meta:
		verbose_name = 'Поставщик'
		verbose_name_plural = 'Поставщики'



			

partners/forms.py
from django import forms
from partners.models import Contractor, Supplier

class ContractorUpdateForm (forms.ModelForm):
	rating = forms.IntegerField(min_value=0, max_value=5, required=True, label='Оценка', help_text='Значение от 0 до 5')

	class Meta:
		model = Contractor
		fields = '__all__'


class SupplierUpdateForm (forms.ModelForm):
	rating = forms.IntegerField(min_value=0, max_value=5, required=True, label='Оценка', help_text='Значение от 0 до 5')

	class Meta:
		model = Supplier
		fields = '__all__'

partners/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import permission_required, login_required
from partners.models import Contractor, Supplier, Comment
from partners.forms import ContractorUpdateForm, SupplierUpdateForm


def partners_list(request):
	contractors = Contractor.objects.all().order_by('-rating')
	suppliers = Supplier.objects.all().order_by('-rating')
	context = {
		'contractors': contractors,
		'suppliers': suppliers
	}
	return render(request, 'partners/partners_list.html', context)


def contractor_detail(request, id):
	partner = get_object_or_404(Contractor, pk = id)
	comments = partner.comments.all()
	context = {'company': partner, 'comments': comments}
	return render(request, 'partners/contractor_detail.html', context)


def supplier_detail(request, id):
	partner = get_object_or_404(Supplier, pk = id)
	comments = partner.comments.all()
	context = {'company': partner, 'comments': comments}
	return render(request, 'partners/supplier_detail.html', context)



@permission_required('pages.change_page')
def update_contractor(request, id=None):
	if id:
		# update existing company
		company_instance = get_object_or_404(Contractor, pk=id)
	else:
		# create new company
		company_instance = None

	if request.method == "POST":
		company_form = ContractorUpdateForm(request.POST, request.FILES, instance = company_instance)
		if company_form.is_valid():
			company = company_form.save()
			messages.success(request, f'Данные компании успешно изменены!')
			return redirect('partners:contractor_detail', company.id)
		else:
			messages.warning(request, f'Возникла ошибка при редактировании данных компании!')
			if id:
				return redirect('partners:contractor_detail', str(id))
			else:
				return redirect('partners:partners_list')
	else:
		company_form = ContractorUpdateForm(instance = company_instance)

	context = {'form': company_form, 'company_id': id}
	return render(request, 'partners/update_contractor_form.html', context)


@permission_required('pages.change_page')
def update_supplier(request, id=None):
	if id:
		# update existing company
		company_instance = get_object_or_404(Supplier, pk=id)
	else:
		# create new company
		company_instance = None

	if request.method == "POST":
		company_form = SupplierUpdateForm(request.POST, request.FILES, instance = company_instance)

		if company_form.is_valid():
			company = company_form.save()
			messages.success(request, f'Данные компании успешно изменены!')
			return redirect('partners:supplier_detail', company.id)
		else:
			messages.warning(request, f'Возникла ошибка при редактировании данных компании!')
			if id:
				return redirect('partners:supplier_detail', str(id))
			else:
				return redirect('partners:partners_list')
	else:
		company_form = SupplierUpdateForm(instance = company_instance)

	context = {'form': company_form, 'company_id': id}
	return render(request, 'partners/update_supplier_form.html', context)


@permission_required('pages.change_page')
def delete_contractor(request, id):
	company = get_object_or_404(Contractor, pk=id)
	company_name = company.company_name
	company.delete()
	messages.info(request, f'Субподрядчик {company_name} удален!')
	return redirect('partners:partners_list')


@permission_required('pages.change_page')
def delete_supplier(request, id):
	company = get_object_or_404(Supplier, pk=id)
	company_name = company.company_name
	company.delete()
	messages.info(request, f'Поставщик {company_name} удален!')
	return redirect('partners:partners_list')



@login_required
def leave_comment(request):
	try:
		object_name = request.POST['object_name']
		object_id = request.POST['object_id']
		if Contractor.__name__ == object_name:
			company = Contractor.objects.get(id=object_id)
		elif Supplier.__name__ == object_name:
			company = Supplier.objects.get(id=object_id)
		else:
			raise ValueError
	except:
		raise Http404("Компания не найдена")

	Comment.objects.create(author = request.user, text = request.POST['text'], content_object=company)

	try:
		next = request.POST['next']
		return HttpResponseRedirect(next) 
	except:
		return HttpResponseRedirect( reverse('partners:partners_list') ) 


@login_required
def delete_comment(request, id):
	comment = get_object_or_404(Comment, pk=id)
	if request.user.has_perm('pages.change_page') or comment.author == request.user:
		comment.delete()
	else:
		messages.warning(request, f'Не достаточно прав для удаления комментария!')

	next = request.GET.get('next', reverse('partners:partners_list'))
	return HttpResponseRedirect(next)

partners/templates/partners/comments.html
{% if comments or user.is_authenticated %}
	<div class="w3-content" style="max-width: 600px;">
		<h3 class="w3-border-bottom">Отзывы</h3>

		{% if comments %}
			{% for c in comments %}
				<div class="card w3-light-grey text-dark my-3">
					<div class="d-flex">
						<strong class="p-1 px-3">{{c.author.username}}</strong>
						<small class="p-1 px-3 ml-auto align-self-center">{{c.pub_date}}</small>

						{% if perms.pages.change_page or c.author == user %}
							<a href="{% url 'partners:delete_comment' c.id %}?next={{request.path}}" class="fas fa-trash-alt btn btn-outline-danger btn-sm align-self-center mx-2" title='Удалить отзыв'></a>
						{% endif %}

					</div>
					<hr class="m-0">
					<div class="p-1 px-3">
						<p class="m-0 p-0">{{c.text|linebreaks}}</p> 
					</div>
				</div>
			{% endfor %}
		{% endif %}

		{% if user.is_authenticated %}
			<p>Оставить отзыв:</p>
			<div class="my-3">
				<form action="{% url 'partners:leave_comment' %}" method="POST">
					{% csrf_token %}
					<input type='hidden' name="user" value="{{user}}"></input>
					<input type='hidden' name="object_name" value="{{object.class_name}}"></input>
					<input type='hidden' name="object_id" value="{{object.id}}"></input>
					<input type='hidden' name="next" value="{{request.path}}"></input>

					<textarea name="text" class="form-control" required placeholder="Отзыв..." rows="4"></textarea>
					<button class="btn btn-outline-success mt-3" type="submit">Оставить отзыв</button>
				</form>
			</div>
		{% endif %}

	</div>
{% endif %}

partners/templates/partners/contractor_detail.html
{% extends 'base.html' %}


{% block content %}
	<div class="my-3">
		<h1 class="w3-light-grey text-dark p-2  mb-3"> 
			{{ company.company_name }} 
			<span class="badge badge-pill float-right 
					{% if company.rating < 2 %} badge-danger 
					{% elif company.rating < 4 %} badge-warning
					{% else %} badge-success 
					{% endif %}
					" title='Рейтинг'> 
				Рейтинг {{ company.rating }} 
			</span>
		</h1>
		<div class="row">
			<div class="col-sm-3">
				<img class="p-2 border w-100" src="{{ company.icon.url }}">
			</div>
			<div class="col-sm-9">
				<h3 class="w3-border-bottom">Тип услуги, деятельность</h3>
				<p class="my-0">{{ company.service|linebreaks }}</p>
				
				<h3 class="w3-border-bottom">Контакты</h3>
				<p class="my-0">{{ company.contacts|linebreaks }}</p>

				{% if company.examples %}
					<h3 class="w3-border-bottom">Примеры работ</h3>
					<p class="my-0">{{ company.examples|linebreaks }}</p>
				{% endif %}
				
			</div>
		</div>


		{% if perms.pages.change_page %}
			<div class="d-flex justify-content-end mt-2 mb-3">
				<a class="btn btn-outline-primary" href="{% url 'partners:update_contractor' company.id %}">Редактировать</a>
			</div>
		{% endif %}

	</div>

	{% include 'partners/comments.html' with object=company %}

{% endblock %}

partners/templates/partners/partners_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
	<h1 class="w3-light-grey text-dark d-flex p-2 mt-3 mb-0"> Субподрядчики 
		{% if perms.pages.change_page %}
		<a class="btn btn-outline-primary ml-auto align-self-center" href="{% url 'partners:add_contractor' %}"> Добавить компанию</a>
		{% endif %}	
	</h1>
	<div class="row mb-3 px-2">
		{% if contractors %}
			{% for company in contractors %}
			  <div class="col-sm-6 mt-3 px-2">
				<div class="media border p-3 h-100">
				  <img class="mr-3 my-2" src="{{ company.icon.url }}" alt="Card image cap" style="max-width: 60px; max-height: 60px;">
				  <div class="media-body">
					<h5 class="card-title"> 
						{{ company.company_name }}

						<span class="badge badge-pill float-right 
								{% if company.rating < 2 %} badge-danger 
								{% elif company.rating < 4 %} badge-warning
								{% else %} badge-success 
								{% endif %}
								" title='Рейтинг'> 
							{{ company.rating }} 
						</span>
					</h5>
			        <p class="card-text"> {{ company.service }} </p>
			        <a href="{% url 'partners:contractor_detail' company.id %}"  class="btn btn-primary btn-sm">Подробнее</a>
				  </div>
				</div>
			  </div>
			{% endfor %}
		{% else %}
			<p class="p-3">
				<span class="text-dark py-2">В данном разделе еще нет компаний.</span>
				{% if perms.pages.change_page %}
				<a class="btn btn-outline-primary ml-4" href="{% url 'partners:add_contractor' %}">Добавить компанию</a>
				{% endif %}	
			</p>
			<hr>
		{% endif %}	
	</div>


	<h1 class="w3-light-grey text-dark d-flex p-2 mt-3 mb-0"> Поставщики 
		{% if perms.pages.change_page %}
		<a class="btn btn-outline-primary ml-auto align-self-center" href="{% url 'partners:add_supplier' %}"> Добавить компанию</a>
		{% endif %}	
	</h1>	
	<div class="row mb-3 px-2">
		{% if suppliers %}
			{% for company in suppliers %}
			  <div class="col-sm-6 mt-3 px-2">
				<div class="media border p-3 h-100">
				  <img class="mr-3 my-2" src="{{ company.icon.url }}" alt="Card image cap" style="max-width: 60px; max-height: 60px;">
				  <div class="media-body">
					<h5 class="card-title"> 
						{{ company.company_name }}

						<span class="badge badge-pill float-right 
								{% if company.rating < 2 %} badge-danger 
								{% elif company.rating < 4 %} badge-warning
								{% else %} badge-success 
								{% endif %}
								" title='Рейтинг'> 
							{{ company.rating }} 
						</span>
					</h5>
			        <p class="card-text"> {{ company.service }} </p>
			        <a href="{% url 'partners:supplier_detail' company.id %}"  class="btn btn-primary btn-sm">Подробнее</a>
				  </div>
				</div>
			  </div>
			{% endfor %}
		{% else %}
			<p class="p-3">
				<span class="text-dark py-2">В данном разделе еще нет компаний.</span>
				{% if perms.pages.change_page %}
				<a class="btn btn-outline-primary ml-4" href="{% url 'partners:add_supplier' %}">Добавить компанию</a>
				{% endif %}	
			</p>
			<hr>
		{% endif %}	
	</div>

{% endblock %}

partners/templates/partners/supplier_detail.html
{% extends 'base.html' %}


{% block content %}
	<div class="my-3">
		<h1 class="w3-light-grey text-dark p-2  mb-3"> 
			{{ company.company_name }} 
			<span class="badge badge-pill float-right 
					{% if company.rating < 2 %} badge-danger 
					{% elif company.rating < 4 %} badge-warning
					{% else %} badge-success 
					{% endif %}
					" title='Рейтинг'> 
				Рейтинг {{ company.rating }} 
			</span>
		</h1>
		<div class="row">
			<div class="col-sm-3">
				<img class="p-2 border w-100" src="{{ company.icon.url }}">
			</div>
			<div class="col-sm-9">
				<h3 class="w3-border-bottom">Тип поставляемого оборудования</h3>
				<p class="my-0">{{ company.service|linebreaks }}</p>
				
				<h3 class="w3-border-bottom">Контакты</h3>
				<p class="my-0">{{ company.contacts|linebreaks }}</p>
				
			</div>
		</div>


		{% if perms.pages.change_page %}
			<div class="d-flex justify-content-end mt-2 mb-3">
				<a class="btn btn-outline-primary" href="{% url 'partners:update_supplier' company.id %}">Редактировать</a>
			</div>
		{% endif %}

	</div>

	{% include 'partners/comments.html' with object=company %}

{% endblock %}

partners/templates/partners/update_contractor_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
	<div class="my-3">
		<h1 class="w3-light-grey text-dark p-2  mb-3"> Субподрядчик </h1>

		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy }}

			<div class="form-groupe d-flex justify-content-center">
				<button class="btn btn-outline-success m-2" type="submit">Применить</button>
				{% if company_id %}
					<a class="btn btn-outline-danger m-2" href="{% url 'partners:contractor_detail' company_id %}">Отмена</a>
					<a class="btn btn-outline-danger m-2 ml-5" href="{% url 'partners:delete_contractor' company_id %}"> <span class="pr-1 fas fa-trash-alt"></span> Удалить</a>					
				{% else %}
					<a class="btn btn-outline-danger m-2" href="{% url 'partners:partners_list' %}">Отмена</a>		
				{% endif %}
			</div>
		</form>
	</div>
{% endblock %}

partners/templates/partners/update_supplier_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
	<div class="my-3">
		<h1 class="w3-light-grey text-dark p-2  mb-3"> Поставщик </h1>

		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy }}

			<div class="form-groupe d-flex justify-content-center">
				<button class="btn btn-outline-success m-2" type="submit">Применить</button>
				{% if company_id %}
					<a class="btn btn-outline-danger m-2" href="{% url 'partners:supplier_detail' company_id %}">Отмена</a>
					<a class="btn btn-outline-danger m-2 ml-5" href="{% url 'partners:delete_supplier' company_id %}"> <span class="pr-1 fas fa-trash-alt"></span> Удалить</a>					
				{% else %}
					<a class="btn btn-outline-danger m-2" href="{% url 'partners:partners_list' %}">Отмена</a>		
				{% endif %}
			</div>
		</form>
	</div>
{% endblock %}