fileslibrary/urls.py
from django.urls import path
from fileslibrary import views

app_name = 'fileslibrary'

urlpatterns = [
	path('', views.home, name='home'),
	path('documents/', views.regulatory_documents, name='regulatory_documents'),
	path('articles/', views.articles, name='articles'),
	path('file/add/', views.add_file, name='add_file'),
	path('file/edit/<int:id>', views.edit_file, name='edit_file'),
	path('topic/add/', views.add_topic, name='add_topic'),
	path('delete/<int:id>', views.delete_file, name='delete_file'),
]

opsi_wiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'), 
    path('page/', include('pages.urls')),
    path('user/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('partners/', include('partners.urls')),
    path('process/', include('processmap.urls')),
    path('library/', include('fileslibrary.urls')),
    path('image-map-creator/', include('imagemap.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('programmer/', views.programmer_pages_list, name='programmer_pages_list'),
    path('constructor/', views.constructor_pages_list, name='constructor_pages_list'),
    path('project_manager/', views.project_manager_pages_list, name='project_manager_pages_list'),
    path('circuit_engineer/', views.circuit_engineer_pages_list, name='circuit_engineer_pages_list'),
    path('detail/<int:id>', views.page_detail, name='detail'),
    path('new/', views.update_page, name='create_page'),
    path('update/<int:id>', views.update_page, name='update_page'),
    path('delete/<int:id>', views.delete_page, name='delete_page'),
]

partners/urls.py
from django.urls import path
from partners import views

app_name = 'partners'

urlpatterns = [
    path('', views.partners_list, name='partners_list'),
    path('contractor/detail/<int:id>', views.contractor_detail, name='contractor_detail'),
    path('contractor/add/', views.update_contractor, name='add_contractor'),
    path('contractor/update/<int:id>', views.update_contractor, name='update_contractor'),
    path('contractor/delete/<int:id>', views.delete_contractor, name='delete_contractor'),

    path('supplier/detail/<int:id>', views.supplier_detail, name='supplier_detail'),
    path('supplier/add/', views.update_supplier, name='add_supplier'),
    path('supplier/update/<int:id>', views.update_supplier, name='update_supplier'),
    path('supplier/delete/<int:id>', views.delete_supplier, name='delete_supplier'),

    path('company/comments/add/', views.leave_comment, name='leave_comment'),
    path('company/comments/delete/<int:id>', views.delete_comment, name='delete_comment'),
]

processmap/urls.py
from django.urls import path
from . import views

app_name = "processmap"

urlpatterns = [
	path('', views.process, name='process'),

]

opsi_wiki/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'opsi_wiki/home.html')

def about(request):
	return render(request, 'opsi_wiki/about.html')

def library(request):
	return render(request, 'opsi_wiki/library.html')

opsi_wiki/templates/opsi_wiki/about.html
{% extends 'base.html' %}

{% block content %}
	<div class="w3-content w3-text-dark-grey pt-2 ">
		<h1 class="w3-xlarge w3-center p-2">Добро пожаловать на Wiki слоя "Системная интеграция"</h1>
		<p class="my-2">Здесь вы найдете массу документов, инструкций и другой полезной информации по основных и вспомогательных процессах Отдела Поддержки Системных Интеграторов, а так же материалы по применяемым технологиям в отделе.</p>
		<p class="my-2">Информация на данном ресурсе разбита на 7 категорий</p>
		<p class="my-2">три общие категории:</p>
		<ul class="my-2">
			<li><a href="http://wiki.kharkov.owen/index.php/%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81_%22%D0%98%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%22._%D0%9D%D0%98%D0%A0_%D0%B8_%D0%9E%D0%9A%D0%A0">Процесс "Системная интеграция"</a> - здесь вы найдете подробное описание процесса Ситсемной интеграции и каждого из его этапов </li>
			<li><a href="{% url 'fileslibrary:home' %}">Библиотека</a> - в данном разделе находятся перечень инфомационных ресурсов компании ОВЕН, библиотека нормативной документации, билиотека специализированной литературы и статей</li>
			<li><a href="http://wiki.kharkov.owen/index.php/%D0%9F%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D1%8B">Наши партнеры</a> - в данном разделе собран перечень организаций, с которыми мы имели положительный опыт сотрудничества</li>
		</ul>
		<p class="my-2">и четыре категории, c материалами для соответствующих специалистов отдела:</p>
		<ul class="my-2">
			<li><a href="{% url 'pages:project_manager_pages_list' %}">Управление проектами</a> - материалы для Руководителей проектов </li>
			<li><a href="{% url 'pages:circuit_engineer_pages_list' %}">Схемотехника</a> - материалы для Инженеров-системотехников </li>
			<li><a href="{% url 'pages:constructor_pages_list' %}">Конструирование</a> - материалы для Инженеров-конструкторов </li>
			<li><a href="{% url 'pages:programmer_pages_list' %}">Программирование</a> - материалы для Инженеров-программистов </li>
		</ul>

		<hr>
		<p>Вопросы и предложения по сайту отрправляйте на почту: <i class="w3-text-blue">a.golovaschenko@owen.ua</i></p>
	</div>
{% endblock %}

opsi_wiki/templates/opsi_wiki/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="w3-content pt-4">
	<div class="row">

		<div class="col-md-4" style="height: 210px;">
			<a href="{% url 'processmap:process' %}" style="text-decoration: none" class="d-flex justify-content-center">
				<img class="hover-image" src="{% static 'img/process.png' %}">
			</a>
			<div class="d-flex justify-content-center">
				<p class="w3-text-blue-grey w3-center p-2">Процесс "Системная интеграция"</p>
			</div>
		</div>

		<div class="col-md-4" style="height: 210px;">
			<a href="{% url 'fileslibrary:home' %}" style="text-decoration: none" class="d-flex justify-content-center">
				<img class="hover-image" src="{% static 'img/library-2.png' %}">
			</a>
			<div class="d-flex justify-content-center">
				<p class="w3-text-blue-grey w3-center p-2">Библиотека</p>
			</div>			
		</div>

		<div class="col-md-4" style="height: 210px;">
			<a href="{% url 'partners:partners_list' %}" style="text-decoration: none" class="d-flex justify-content-center">
				<img class="hover-image" src="{% static 'img/partners.png' %}">
			</a>
			<div class="d-flex justify-content-center">
				<p class="w3-text-blue-grey w3-center p-2">Наши партнеры</p>
			</div>			
		</div>
	</div>
</div>

<div class="w3-content pt-2">
	<div class="row">
		<div class="col-md-6 col-lg-3" style="height: 210px;">
			<a href="{% url 'pages:project_manager_pages_list' %}" style="text-decoration: none" class="d-flex justify-content-center">
				<img class="hover-image" src="{% static 'img/icon_project_managment.png' %}">
			</a>
			<div class="d-flex justify-content-center">
				<p class="w3-text-blue-grey p-2">Управление проектами</p>
			</div>
		</div>

		<div class="col-md-6 col-lg-3" style="height: 210px;">
			<a href="{% url 'pages:circuit_engineer_pages_list' %}" style="text-decoration: none" class="d-flex justify-content-center">
				<img class="hover-image" src="{% static 'img/icon_electrical_scheme.png' %}">
			</a>
			<div class="d-flex justify-content-center">
				<p class="w3-text-blue-grey p-2">Схемотехника</p>
			</div>			
		</div>

		<div class="col-md-6 col-lg-3" style="height: 210px;">
			<a href="{% url 'pages:constructor_pages_list' %}" style="text-decoration: none" class="d-flex justify-content-center">
				<img class="hover-image" src="{% static 'img/icon_3d_modeling.png' %}">
			</a>
			<div class="d-flex justify-content-center">
				<p class="w3-text-blue-grey p-2">Конструирование</p>
			</div>			
		</div>

		<div class="col-md-6 col-lg-3" style="height: 210px;">
			<a href="{% url 'pages:programmer_pages_list' %}" style="text-decoration: none" class="d-flex justify-content-center">
				<img class="hover-image" src="{% static 'img/icon_programming.png' %}">
			</a>
			<div class="d-flex justify-content-center">
				<p class="w3-text-blue-grey p-2">Программирование</p>
			</div>			
		</div>
	</div>
</div>

<hr class="mt-0">
<div class="w3-content w3-text-dark-grey mb-4">
	<h1 class="w3-xlarge w3-center p-2">Добро пожаловать на Wiki слоя "Системная интеграция"</h1>
	<p class="my-2">Здесь вы найдете массу документов, инструкций и другой полезной информации по основных и вспомогательных процессах Отдела Поддержки Системных Интеграторов, а так же материалы по применяемым технологиям в отделе.</p>
	<p class="my-2">Информация на данном ресурсе разбита на 7 категорий</p>
	<p class="my-2">три общие категории:</p>
	<ul class="my-2">
		<li><a href="http://wiki.kharkov.owen/index.php/%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81_%22%D0%98%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%22._%D0%9D%D0%98%D0%A0_%D0%B8_%D0%9E%D0%9A%D0%A0">Процесс "Системная интеграция"</a> - здесь вы найдете подробное описание процесса Ситсемной интеграции и каждого из его этапов </li>
		<li><a href="{% url 'fileslibrary:home' %}">Библиотека</a> - в данном разделе находятся перечень инфомационных ресурсов компании ОВЕН, библиотека нормативной документации, билиотека специализированной литературы и статей</li>
		<li><a href="http://wiki.kharkov.owen/index.php/%D0%9F%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D1%8B">Наши партнеры</a> - в данном разделе собран перечень организаций, с которыми мы имели положительный опыт сотрудничества</li>
	</ul>
	<p class="my-2">и четыре категории, c материалами для соответствующих специалистов отдела:</p>
	<ul class="my-2">
		<li><a href="{% url 'pages:project_manager_pages_list' %}">Управление проектами</a> - материалы для Руководителей проектов </li>
		<li><a href="{% url 'pages:circuit_engineer_pages_list' %}">Схемотехника</a> - материалы для Инженеров-системотехников </li>
		<li><a href="{% url 'pages:constructor_pages_list' %}">Конструирование</a> - материалы для Инженеров-конструкторов </li>
		<li><a href="{% url 'pages:programmer_pages_list' %}">Программирование</a> - материалы для Инженеров-программистов </li>
	</ul>
</div>
{% endblock %}

opsi_wiki/templates/opsi_wiki/information_resources.html
information_resources.html

opsi_wiki/templates/opsi_wiki/library.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="p-3">
		<div class="row">
		<div class="col-md-4 px-2">
			<div class="card hover-card w3-hover-border-blue p-3 pt-3 h-100 w3-pale-green" style="min-height: 210px;">
				<a href="http://wiki.kharkov.owen/index.php/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D1%8B" style="text-decoration: none" class="d-flex justify-content-center">
					<img style="width: 130px; height: 130px;" src="{% static 'img/web.png' %}">
				</a>
				<div class="d-flex justify-content-center">
					<b><p class="text-secondary text-center p-2 mb-0 hover-card-header">Информационные ресурсы</p></b>
				</div>
				<hr class="m-0">
				<div class="py-3 text-dark">
					<p class="mb-2">В данном разделе собраны все информационные ресурсы компании ОВЕН.</p>
					<p class="mb-2">Здесь вы найдете ссылки на SVN, Redmine, Ссылки на страницы компании в различных социальных сеьях и многое другое.</p>
				</div>
				<div class="d-flex h-100">
					<a href="http://wiki.kharkov.owen/index.php/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D1%8B"  class="btn btn-primary btn-sm align-self-end ml-auto">Подробней</a>
				</div>
			</div>
		</div>

		<div class="col-md-4 px-2">
			<div class="card hover-card w3-hover-border-blue p-3 pt-3 h-100 w3-pale-blue" style="min-height: 210px;">
				<a href="{% url 'fileslibrary:home' %}" style="text-decoration: none" class="d-flex justify-content-center">
					<img style="width: 130px; height: 130px;" src="{% static 'img/standard.png' %}">
				</a>
				<div class="d-flex justify-content-center">
					<b><p class="text-secondary text-center p-2 mb-0 hover-card-header">Нормативная документация</p></b>
				</div>		
				<hr class="m-0">
				<div class="py-3 text-dark">
					<p class="mb-2">В данном разделе собраны нормативные документы, которыми должен руководствовоться каждый инженер.</p>
					<p class="mb-2">Здесь вы найдете Государственные стандарты (ГОСТы), Международные стандарты (ISO), Отраслевые стандарты и многое другое.</p>
				</div>
				<div class="d-flex h-100">
					<a href="{% url 'fileslibrary:home' %}"  class="btn btn-primary btn-sm align-self-end ml-auto">Подробней</a>
				</div>	
			</div>
		</div>

		<div class="col-md-4 px-2">
			<div class="card hover-card w3-hover-border-blue p-3 pt-3 h-100 w3-pale-yellow" style="min-height: 210px;">
				<a href="#" style="text-decoration: none" class="d-flex justify-content-center">
					<img style="width: 130px; height: 130px;" src="{% static 'img/books.png' %}">
				</a>
				<div class="d-flex justify-content-center">
					<b><p class="text-secondary text-center p-2 mb-0 hover-card-header">Литература</p></b>
				</div>
				<hr class="m-0">
				<div class="py-3 text-dark">
					<p class="mb-2">В данном разделе собраны книги, статьи, журналы и другая полезная профессиональная литература.</p>
				</div>
				<div class="d-flex h-100">
					<a href="#"  class="btn btn-primary btn-sm align-self-end ml-auto">Подробней</a>
				</div>			
			</div>
		</div>
		</div>
	</div>

{% endblock %}

opsi_wiki/templates/opsi_wiki/system_integration_process.html
system_integration_process.html