opsi_wiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'), 
    path('page/', include('pages.urls')),
    path('user/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('partners/', include('partners.urls')),
    path('process/', include('processmap.urls')),
    path('library/', include('fileslibrary.urls')),
    path('image-map-creator/', include('imagemap.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('programmer/', views.programmer_pages_list, name='programmer_pages_list'),
    path('constructor/', views.constructor_pages_list, name='constructor_pages_list'),
    path('project_manager/', views.project_manager_pages_list, name='project_manager_pages_list'),
    path('circuit_engineer/', views.circuit_engineer_pages_list, name='circuit_engineer_pages_list'),
    path('detail/<int:id>', views.page_detail, name='detail'),
    path('new/', views.update_page, name='create_page'),
    path('update/<int:id>', views.update_page, name='update_page'),
    path('delete/<int:id>', views.delete_page, name='delete_page'),
]

pages/models.py
from django.db import models
from django.urls import reverse
import os
from ckeditor.fields import RichTextField 


class Category (models.Model):
    SOFTWARE_DEVELOPMENT = 'SOFT_DEV'
    CONSTRUCTION = 'CONSTRUCT'
    PROJECT_MANAGMENT = 'PROJ_MANAG'
    CIRCUIT_ENGINEERING = 'CIRC_ENG'
    PROCESS_SYSTEM_INTEGRATION = 'PROC_SI'

    CATEGORY_CHOICES = [
        (None, '---------'),
        (SOFTWARE_DEVELOPMENT, 'Программирование'),
        (CONSTRUCTION, 'Конструирование'),
        (PROJECT_MANAGMENT, 'Управление проектами'),
        (CIRCUIT_ENGINEERING, 'Схемотехника'),
        (PROCESS_SYSTEM_INTEGRATION, 'Процесс "Системная интеграция"'),
    ]

    name = models.CharField(max_length=20, choices=CATEGORY_CHOICES,
            verbose_name='Название', unique=True )
    order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)

    def __str__ (self):
        return self.get_name_display()

    class Meta():
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def get_url(self):
        return Category.get_url_by_name(self.name)

    def get_url_by_name(name):
        urls = {
            Category.SOFTWARE_DEVELOPMENT : reverse('pages:programmer_pages_list'),
            Category.CONSTRUCTION : reverse('pages:constructor_pages_list'),
            Category.PROJECT_MANAGMENT : reverse('pages:project_manager_pages_list'),
            Category.CIRCUIT_ENGINEERING : reverse('pages:circuit_engineer_pages_list'),
            Category.PROCESS_SYSTEM_INTEGRATION : reverse('processmap:process'),
        }
        return urls.get(name, reverse('home'))


class Topic (models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)
    description = models.TextField(verbose_name='Описание', blank=True)
    order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)

    def __str__ (self):
        return self.name

    class Meta():
        verbose_name = "Тема"
        verbose_name_plural = "Темы"


class Page(models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, verbose_name='Тема', on_delete=models.CASCADE) 
    short_description = RichTextField(verbose_name='Краткое описание', blank=True)

    def __str__(self):
        return str(self.category) + ': ' + self.name

    class Meta():
        verbose_name = "Страница"
        verbose_name_plural = "Страницы"


class Section(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    headline = models.CharField(verbose_name='Оглавление', max_length=200, blank=True)
    content = RichTextField(verbose_name='Раздел', blank=True)

    def __str__(self):
        return self.headline

    class Meta():
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"

def file_storage_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/uploads/files_<page.id>/<filename>
    return 'uploads/files_{0}/{1}'.format(instance.page.id, filename)

class File(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    upload = models.FileField(verbose_name='Файл', upload_to=file_storage_path, max_length=500)
    alter_name = models.CharField(verbose_name='Переименовать файл', max_length=200, blank=True)
    comment = models.CharField(verbose_name='Комментарий', max_length=200, blank=True)

    def filename(self):
        if self.alter_name:
            return self.alter_name
        else:
            return os.path.basename(self.upload.name).replace('_', ' ')

    def __str__(self):
        return self.filename()

    class Meta():
        verbose_name = "Файл"
        verbose_name_plural = "Файлы"

class Link(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя', max_length=200, blank=True)
    link = models.TextField(verbose_name='Ссылка')

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "Внешняя ссылка"
        verbose_name_plural = "Внешние ссылки"

class Reference(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя', max_length=200)
    link = models.TextField(verbose_name='Ссылка', blank=True)
    author = models.CharField(verbose_name='Автор', max_length=200, blank=True)
    pub_date = models.CharField(verbose_name='Дата публикации', max_length=200, blank=True)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "Литература"
        verbose_name_plural = "Литература"

pages/templates/pages/contents_bar.html
<div class="col-3 d-none d-md-inline my-3 w3-border-right" style="min-width: 250px">
<div class="sticky-top" style="top: 15px">
	<ul class="list-group list-group-flush">

	{% for category in contents %}

		<!-- Categories -->
		{% if category.active == True %}  
		<li class="list-group-item-primary d-flex align-items-center w3-border-bottom p-0">
			<h4 class="w3-medium text-left p-2 m-0">
				<a class="" href="{{ category.url }}">{{ category.name }}</a>
			</h4>
			{% if category.topics %}
				<button class="btn-toggle-category-collapse btn fas fa-angle-down ml-auto mr-1 text-dark" data-toggle="collapse" data-target="#id_category_collapse_item_{{ forloop.counter }}">
				</button>
			{% endif %}
		</li>
		{% else %}
		<li class="w3-light-grey d-flex align-items-center w3-border-bottom p-0">
			<h4 class="w3-medium text-left p-2 m-0">
				<a class="" href="{{ category.url }}">{{ category.name }}</a>
			</h4>
			{% if category.topics %}
				<button class="btn-toggle-category-collapse btn fas fa-angle-down ml-auto mr-1 text-dark" data-toggle="collapse" data-target="#id_category_collapse_item_{{ forloop.counter }}">
				</button>
			{% endif %}
		</li>
		{% endif %}

		<!-- Category content -->
		<div class="category-collapse collapse" id="id_category_collapse_item_{{ forloop.counter }}">
		<ul class="list-group list-group-flush">
		{% for topic in category.topics %}
			<li class="d-flex align-items-center p-0 w3-border-bottom">
				<h4 class="small text-left p-2 m-0">
					{{ topic.name }}
				</h4>
				{% if topic.pages %}
					<button class="btn-toggle-topic-collapse btn fas fa-angle-down ml-auto mr-1 py-1 text-dark" data-toggle="collapse" data-target="#id_topic_collapse_item_{{ forloop.parentloop.counter }}{{ forloop.counter }}">
					</button>
				{% endif %}
			</li>

			<div class="topic-collapse collapse w3-border-bottom" id="id_topic_collapse_item_{{ forloop.parentloop.counter }}{{ forloop.counter }}">
			<ul class="list-group list-group-flush small py-2">
				{% for page in topic.pages %}	
				<a href="{{ page.url }}" class="text-left p-0 m-0" style="text-decoration: none;">
					<li class="ml-4 w3-hover-pale-blue w3-hover-text-indigo"> {{ page.name }} </li>
				</a>
				{% endfor %}
			</ul>
			</div>	
		{% endfor %}
		</ul>
		</div>

	{% endfor %}
	</ul>
</div>
</div>



<script>
	jQuery('button.btn-toggle-category-collapse').click( function(e) {
	    jQuery('.category-collapse.collapse').collapse('hide');
	});

	jQuery('button.btn-toggle-topic-collapse').click( function(e) {
	    jQuery('.topic-collapse.collapse').collapse('hide');
	});	
</script>

pages/templates/pages/file_upload_form.html
{{ form.non_field_errors }}

{% for hidden_field in form.hidden_fields %}
	{{ hidden_field.errors }}
	{{ hidden_field }}
{% endfor %}

<div id="file_form_set">
    <div class="row">
	    <div class="col-md-4 my-1">
	        {{ form.upload }}
	        {% if form.upload.value %}
		        <span class="small" style="display: block">
		        	На данный момент: <a class="text-info" href='{{ form.upload.value.url }}'>{{ form.upload.value }}</a>
		    	</span>    
		    {% endif %}
	    </div>
	    <div class="col-md-6 my-1">
	    	<span style="width:100px; display: inline-block;">Комментарий:</span>
	        {{ form.comment }}
	    </div>
	    <div class="col-md-2 my-1">
	        {{ form.DELETE }} 
	        Удалить
	    </div>
    </div>
</div>

 

pages/templates/pages/link_add_form.html
{{ form.non_field_errors }}

{% for hidden_field in form.hidden_fields %}
	{{ hidden_field.errors }}
	{{ hidden_field }}
{% endfor %}

<div id="file_form_set">
    <div class="row">
	    <div class="col-md-5 my-1">
	    	<span style="width:60px; display: inline-block;">Имя:</span>
	        {{ form.name }}
	    </div>
	    <div class="col-md-5 my-1">
	    	<span style="width:60px; display: inline-block;">Ссылка:</span>
	        {{ form.link }}
	    </div>
	    <div class="col-md-2 my-1">
	        {{ form.DELETE }} 
	        Удалить
	    </div>
    </div>
</div>

 

pages/templates/pages/page_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content_max_width %} 1500px; {% endblock %}
{% block alert_max_width %} 1500px; {% endblock %}


{% block content %}
<div class="row">

	{% include 'pages/contents_bar.html' with contents=contents %}

	<div class="col">
		<h1 class="w3-section w3-padding w3-xlarge w3-border-bottom w3-light-grey w3-center text-dark">{{ page.name }}</h1>
		<div class="rich-text-area">
			<p>{{ page.short_description | safe }}</p>
		</div>

		{% for section in page.section_set.all %}
			<h2 class="w3-margin-top w3-xlarge w3-border-bottom">{{ section.headline }}</h2>
			<div class="rich-text-area">
				<p >{{ section.content | safe }}</p>
			</div>
		{% endfor %}


		{% if page.file_set.all %}
			<h2 class="w3-margin-top w3-xlarge w3-border-bottom">Файлы</h2>
			<ul style="padding-left: 0px; list-style-type: none; ">
				{% for file in page.file_set.all %}
					<li>
						<i class="far fa-file-alt pr-2"></i>
						<a href="{{ file.upload.url }}" style="text-decoration: none" class="w3-text-indigo w3-hover-text-blue">{{file.filename}}</a> {% if file.comment %} - <span>{{file.comment}}</span> {% endif %}
					</li>
				{% endfor %}
			</ul>
		{% endif %}


		{% if page.link_set.all %}
			<h2 class="w3-margin-top w3-xlarge w3-border-bottom">Ссылки</h2>
			<ul style="padding-left: 0px; list-style-type: none; ">
				{% for link in page.link_set.all %}
					<li>
						<i class="fas fa-link pr-2"></i>
						<a href="{{ link.link }}" style="text-decoration: none" class="w3-text-indigo w3-hover-text-blue">{{link.name}}</a>
					</li>
				{% endfor %}
			</ul>
		{% endif %}
		

		{% if page.reference_set.all %}
			<h2 class="w3-margin-top w3-xlarge w3-border-bottom">Литература</h2>
			
			<ul style="padding-left: 0px; list-style-type: none; ">
				{% for ref in page.reference_set.all %}
				<li>
					<i class="fas fa-book pr-2"></i>
					{% if ref.link %}
						<a href="{{ ref.link }}" style="text-decoration: none" class="w3-text-indigo w3-hover-text-blue">{{ref.name}}.</a>
					{% else %}
						{{ref.name}}.
					{% endif %}
					{% if ref.author %} <span>{{ ref.author }}.</span> {% endif %} 
					{% if ref.pub_date %} <span>{{ ref.pub_date }}.</span> {% endif %}
				</li>
				{% endfor %}
			</ul>
		{% endif %}

		{% if perms.pages.change_page %}
		<div class="d-flex justify-content-end mt-2 mb-4">
			<a class="btn btn-outline-primary" href="{% url 'pages:update_page' page.id %}">Редактировать</a>
		</div>
		{% endif %}

	</div>
</div>
{% endblock %}

pages/templates/pages/pages_list.html
{% extends 'base.html' %}

{% block content_max_width %} 1500px; {% endblock %}
{% block alert_max_width %} 1500px; {% endblock %}


{% block content %}
	{% include 'pages/pages_list_content.html' %}
{% endblock %}

pages/templates/pages/pages_list_content.html
<div class="row">

	{% include 'pages/contents_bar.html' with contents=contents %}

	<div class="col">
	{% if topics %}
		{% for topic, pages in topics.items %}
			<ul class="w3-ul mt-3">
				<li class="w3-light-grey w3-text-dark-grey py-0" style="padding-top: 2px; padding-bottom: 2px;">
					<h2 class="w3-xlarge my-1" >{{ topic }}</h2>
				</li>
				{% for p in pages %}
					<li class="p-1">
						<div class="d-flex">
							<a href="{% url 'pages:detail' p.id %}" style="text-decoration: none;" class="align-self-center">{{ p.name }}</a>
							<button class="fas fa-share-alt btn btn-outline-info ml-auto btn-sm" onclick="copyLink('{{ request.scheme }}://{{ request.get_host }}{% url 'pages:detail' p.id %}')" title='Копировать ссылку'></button>
							{% if perms.pages.change_page %}
							<a href="{% url 'pages:delete_page' p.id %}?next={{request.path}}" class="fas fa-trash-alt btn btn-outline-danger btn-sm ml-3" title='Удалить страницу'></a>
							{% endif %}
						</div>
					</li>
			 	{% endfor %}
			</ul>
		{% endfor %}

		{% if perms.pages.change_page %}
		<div class="d-flex justify-content-end mt-4 mb-4">
			<a class="btn btn-outline-primary" href="{% url 'pages:create_page'%}">Создать статью</a>
		</div>
		{% endif %}

	{% else %}
		<p class="pt-4">
			<span class="text-dark py-2">В данном разделе еще нет статей.</span>
			{% if perms.pages.change_page %}
			<a class="btn btn-outline-primary ml-4" href="{% url 'pages:create_page'%}">Создать статью</a>
			{% endif %}	
		</p>
		<hr>
	{% endif %}
	</div>

</div>

pages/templates/pages/reference_add_form.html
{{ form.non_field_errors }}

{% for hidden_field in form.hidden_fields %}
	{{ hidden_field.errors }}
	{{ hidden_field }}
{% endfor %}

<div id="file_form_set">
    <div class="row">
	    <div class="col-md-3 my-1">
	    	<span>Название:</span>
	        {{ form.name }}
	    </div>
	    <div class="col-md-3 my-1">
	    	<span>Ссылка:</span>	    	
	        {{ form.link }}
	    </div>
	    <div class="col-md-3 my-1">
	    	<span>Автор:</span>	    	
	        {{ form.author }}
	    </div>
	    <div class="col-md-2 my-1">
	    	<span class="text-nowrap">Дата публикации:</span>	    	
	        {{ form.pub_date }}
	    </div>	    	    
	    <div class="col-md-1 my-1">
	    	<span>Удалить</span>	    	
	        {{ form.DELETE }} 
	    </div>
    </div>
</div>

 

pages/templates/pages/update_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
	<div class="pt-2">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				{{ page_form|crispy }}
				{{ page_form.media }}
			
				{{ section_forms.management_form|crispy }}
				<div id="section_form_set">
			    {% for form in section_forms.forms %}
			    	<hr class="w3-bottombar border-dark">
				    <div>
				        {{ form|crispy }}
				    </div>
			    {% endfor %}
				</div>
				<input type="button" class="btn btn-outline-primary" value="Добавить раздел" id="section_add_more">
				<hr class="w3-bottombar border-dark">

				{{ file_forms.management_form }}
				<div id="file_form_set">
				{% for form in file_forms.forms %}
					{% include 'pages/file_upload_form.html' with form=form %}
					<hr>
				{% endfor %}
				</div>
				<input type="button" class="btn btn-outline-primary" value="Добавить файл" id="file_add_more">
				<hr class="w3-bottombar border-dark">

				{{ link_forms.management_form }}
				<div id="link_form_set">
				{% for form in link_forms.forms %}
					{% include 'pages/link_add_form.html' with form=form %}
					<hr>
				{% endfor %}
				</div>
				<input type="button" class="btn btn-outline-primary" value="Добавить ссылку" id="link_add_more">
				<hr class="w3-bottombar border-dark">

				{{ reference_forms.management_form }}
				<div id="reference_form_set">
				{% for form in reference_forms.forms %}
					{% include 'pages/reference_add_form.html' with form=form %}
					<hr>
				{% endfor %}
				</div>
				<input type="button" class="btn btn-outline-primary" value="Добавить литературу" id="reference_add_more">
				<hr class="w3-bottombar border-dark">				

			<div class="form-groupe d-flex justify-content-center">
				<button class="btn btn-outline-success m-2" type="submit">Применить</button>
				<a class="btn btn-outline-danger m-2" href="{% if page_id %} {% url 'pages:detail' page_id %} {% else %} {% url 'home' %} {% endif %}">Отмена</a>
			</div>
		</form>					
	</div>

	<div id="section_empty_form" style="display:none">
		<div id="id_form-__prefix__">
			<hr class="w3-bottombar border-dark">
	        {{ section_forms.empty_form|crispy }}
        </div>
	</div>

	<div id="file_empty_form" style="display:none">
		{% include 'pages/file_upload_form.html' with form=file_forms.empty_form %}
		<hr>
	</div>

	<div id="link_empty_form" style="display:none">
		{% include 'pages/link_add_form.html' with form=link_forms.empty_form %}
		<hr>
	</div>

	<div id="reference_empty_form" style="display:none">
		{% include 'pages/reference_add_form.html' with form=reference_forms.empty_form %}
		<hr>
	</div>
{% endblock %}


{% block scripts %}
	{{ block.super }}

	<script>
	    $('#section_add_more').click( function() {
	        cloneMore('#section_empty_form' ,'#section_form_set', 'section_set');
	    });

	    $('#file_add_more').click( function() {
	        cloneMore('#file_empty_form' ,'#file_form_set', 'file_set');
	    });

	    $('#link_add_more').click( function() {
	        cloneMore('#link_empty_form' ,'#link_form_set', 'link_set');
	    });

	    $('#reference_add_more').click( function() {
	        cloneMore('#reference_empty_form' ,'#reference_form_set', 'reference_set');
	    });	    

	</script>

	<script>
		function cloneMore(empty_form, block_to_append, form_prefix) {
	    	var newElement = $(empty_form).clone(true);
		    var total = $('#id_' + form_prefix + '-TOTAL_FORMS').val();

		    $(block_to_append).append(newElement.html().replace(/__prefix__/g, total));

	        $('#id_form-' + total).find('textarea').each(function() {
		      CKEDITOR.replace( $(this).attr('id'), {
		      	customConfig: "{% static '/ckeditor/js/config.js' %}"
		      	});
		    });

		    total++;
		    $('#id_' + form_prefix + '-TOTAL_FORMS').val(total);
	    }
	</script>

{% endblock %}