fileslibrary/urls.py
from django.urls import path
from fileslibrary import views

app_name = 'fileslibrary'

urlpatterns = [
	path('', views.home, name='home'),
	path('documents/', views.regulatory_documents, name='regulatory_documents'),
	path('articles/', views.articles, name='articles'),
	path('file/add/', views.add_file, name='add_file'),
	path('file/edit/<int:id>', views.edit_file, name='edit_file'),
	path('topic/add/', views.add_topic, name='add_topic'),
	path('delete/<int:id>', views.delete_file, name='delete_file'),
]

opsi_wiki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'), 
    path('page/', include('pages.urls')),
    path('user/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('partners/', include('partners.urls')),
    path('process/', include('processmap.urls')),
    path('library/', include('fileslibrary.urls')),
    path('image-map-creator/', include('imagemap.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('programmer/', views.programmer_pages_list, name='programmer_pages_list'),
    path('constructor/', views.constructor_pages_list, name='constructor_pages_list'),
    path('project_manager/', views.project_manager_pages_list, name='project_manager_pages_list'),
    path('circuit_engineer/', views.circuit_engineer_pages_list, name='circuit_engineer_pages_list'),
    path('detail/<int:id>', views.page_detail, name='detail'),
    path('new/', views.update_page, name='create_page'),
    path('update/<int:id>', views.update_page, name='update_page'),
    path('delete/<int:id>', views.delete_page, name='delete_page'),
]

fileslibrary/models.py
from django.db import models
import os


class Topic(models.Model):
	REGULATORY_DOCUMENTS = 'RD'
	ARTICLES = 'AR'

	TOPIC_CATEGORI_CHOICES = [
		(REGULATORY_DOCUMENTS, 'Нормативная документация'),
		(ARTICLES, 'Литература'),
	]

	category = models.CharField(max_length=10, choices=TOPIC_CATEGORI_CHOICES, verbose_name='Категория')
	name = models.CharField(max_length=100, verbose_name='Название')

	def __str__(self):
		return self.get_category_display() + ': ' + self.name

	class Meta:
		verbose_name = 'Тема'
		verbose_name_plural = 'Темы'



def file_storage_path(instance, filename):
	# file will be uploaded to MEDIA_ROOT/fileslibrary/topic_<topic.id>/<filename>
	return 'fileslibrary/topic_{0}/{1}'.format(instance.topic.id, filename)

class File(models.Model):
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='Тема')
	upload = models.FileField(upload_to=file_storage_path, verbose_name='Файл', max_length=500)
	alter_name = models.CharField(verbose_name='Переименовать файл', max_length=200, blank=True)
	description = models.TextField(verbose_name='Описание', blank=True)

	def file_extension(self):
		return self.upload.name.split('.')[-1].lower()

	def file_name(self):
		if self.alter_name:
			return self.alter_name
		else:
			return os.path.basename(self.upload.name).replace('_', ' ')

	def __str__ (self):
		return self.file_name()

	class Meta:
		verbose_name = 'Файл'
		verbose_name_plural = 'Файлы'

pages/models.py
from django.db import models
from django.urls import reverse
import os
from ckeditor.fields import RichTextField 


class Category (models.Model):
    SOFTWARE_DEVELOPMENT = 'SOFT_DEV'
    CONSTRUCTION = 'CONSTRUCT'
    PROJECT_MANAGMENT = 'PROJ_MANAG'
    CIRCUIT_ENGINEERING = 'CIRC_ENG'
    PROCESS_SYSTEM_INTEGRATION = 'PROC_SI'

    CATEGORY_CHOICES = [
        (None, '---------'),
        (SOFTWARE_DEVELOPMENT, 'Программирование'),
        (CONSTRUCTION, 'Конструирование'),
        (PROJECT_MANAGMENT, 'Управление проектами'),
        (CIRCUIT_ENGINEERING, 'Схемотехника'),
        (PROCESS_SYSTEM_INTEGRATION, 'Процесс "Системная интеграция"'),
    ]

    name = models.CharField(max_length=20, choices=CATEGORY_CHOICES,
            verbose_name='Название', unique=True )
    order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)

    def __str__ (self):
        return self.get_name_display()

    class Meta():
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def get_url(self):
        return Category.get_url_by_name(self.name)

    def get_url_by_name(name):
        urls = {
            Category.SOFTWARE_DEVELOPMENT : reverse('pages:programmer_pages_list'),
            Category.CONSTRUCTION : reverse('pages:constructor_pages_list'),
            Category.PROJECT_MANAGMENT : reverse('pages:project_manager_pages_list'),
            Category.CIRCUIT_ENGINEERING : reverse('pages:circuit_engineer_pages_list'),
            Category.PROCESS_SYSTEM_INTEGRATION : reverse('processmap:process'),
        }
        return urls.get(name, reverse('home'))


class Topic (models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)
    description = models.TextField(verbose_name='Описание', blank=True)
    order = models.PositiveSmallIntegerField(verbose_name='Порядок отображения', default=0)

    def __str__ (self):
        return self.name

    class Meta():
        verbose_name = "Тема"
        verbose_name_plural = "Темы"


class Page(models.Model):
    name = models.CharField(verbose_name='Название', max_length=200)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, verbose_name='Тема', on_delete=models.CASCADE) 
    short_description = RichTextField(verbose_name='Краткое описание', blank=True)

    def __str__(self):
        return str(self.category) + ': ' + self.name

    class Meta():
        verbose_name = "Страница"
        verbose_name_plural = "Страницы"


class Section(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    headline = models.CharField(verbose_name='Оглавление', max_length=200, blank=True)
    content = RichTextField(verbose_name='Раздел', blank=True)

    def __str__(self):
        return self.headline

    class Meta():
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"

def file_storage_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/uploads/files_<page.id>/<filename>
    return 'uploads/files_{0}/{1}'.format(instance.page.id, filename)

class File(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    upload = models.FileField(verbose_name='Файл', upload_to=file_storage_path, max_length=500)
    alter_name = models.CharField(verbose_name='Переименовать файл', max_length=200, blank=True)
    comment = models.CharField(verbose_name='Комментарий', max_length=200, blank=True)

    def filename(self):
        if self.alter_name:
            return self.alter_name
        else:
            return os.path.basename(self.upload.name).replace('_', ' ')

    def __str__(self):
        return self.filename()

    class Meta():
        verbose_name = "Файл"
        verbose_name_plural = "Файлы"

class Link(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя', max_length=200, blank=True)
    link = models.TextField(verbose_name='Ссылка')

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "Внешняя ссылка"
        verbose_name_plural = "Внешние ссылки"

class Reference(models.Model):
    page = models.ForeignKey(Page, verbose_name='Страница', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Имя', max_length=200)
    link = models.TextField(verbose_name='Ссылка', blank=True)
    author = models.CharField(verbose_name='Автор', max_length=200, blank=True)
    pub_date = models.CharField(verbose_name='Дата публикации', max_length=200, blank=True)

    def __str__(self):
        return self.name

    class Meta():
        verbose_name = "Литература"
        verbose_name_plural = "Литература"

fileslibrary/forms.py
from django import forms
from fileslibrary.models import File, Topic


class FileAddForm(forms.ModelForm):
	class Meta():
		model = File
		fields = '__all__'
			

class TopicAddForm(forms.ModelForm):
	class Meta():
		model = Topic
		fields = '__all__'

fileslibrary/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404, get_list_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect

from fileslibrary.models import Topic, File
from fileslibrary.forms import FileAddForm, TopicAddForm


def home(request):
	return render(request, 'fileslibrary/home.html')


def regulatory_documents(request):
	context = _get_topic_contents(Topic.REGULATORY_DOCUMENTS)
	return render(request, 'fileslibrary/files_list.html', context)


def articles(request):
	context = _get_topic_contents(Topic.ARTICLES)
	return render(request, 'fileslibrary/files_list.html', context)


def _get_topic_contents(category):
	topics = Topic.objects.filter(category = category)

	contents = []
	for topic in topics:
		files = topic.file_set.all()
		if files:
			cont = {}
			cont['topic'] = topic.name
			cont['files'] = files
			contents.append(cont)

	return {'contents': contents}



@permission_required('pages.change_page')
def add_file(request):
	if request.method == "POST":
		file_form = FileAddForm(request.POST, request.FILES)
		if file_form.is_valid():
			file_form.save()
			messages.success(request, 'Файл успешно сохранен!')
		else:
			messages.warning(request, 'Возникла ошибка при сохранении файла!')
		next = request.POST.get('next', reverse('fileslibrary:home'))
		return HttpResponseRedirect(next)
	else:
		file_form = FileAddForm()

	next = request.GET.get('next', reverse('fileslibrary:home'))	
	context = {'form':file_form, 'next': next}
	return render(request, 'fileslibrary/file_add_form.html', context)


@permission_required('pages.change_page')
def edit_file(request, id):
	instance = get_object_or_404(File, pk=id)
	if request.method == "POST":
		file_form = FileAddForm(request.POST, request.FILES, instance = instance)
		if file_form.is_valid():
			file_form.save()
			messages.success(request, 'Файл успешно сохранен!')
		else:
			messages.warning(request, 'Возникла ошибка при сохранении файла!')
		next = request.POST.get('next', reverse('fileslibrary:home'))
		return HttpResponseRedirect(next)
	else:
		file_form = FileAddForm(instance = instance)
	
	next = request.GET.get('next', reverse('fileslibrary:home'))
	context = {'form':file_form, 'next': next}
	return render(request, 'fileslibrary/file_edit_form.html', context)


@permission_required('pages.change_page')
def delete_file(request, id):
	file = get_object_or_404(File, pk=id)
	name = file.file_name()
	file.delete()
	messages.info(request, f'Документ "{name}" удален!')
	next = request.GET.get('next', reverse('fileslibrary:home'))
	return HttpResponseRedirect(next)


@permission_required('pages.change_page')
def add_topic(request):
	if request.method == "POST":
		topic_form = TopicAddForm(request.POST, request.FILES)
		if topic_form.is_valid():
			topic_form.save()
			messages.success(request, 'Тема успешно создана!')
		else:
			messages.warning(request, 'Возникла ошибка при создании темы!')
		next = request.POST.get('next', reverse('fileslibrary:home'))
		return HttpResponseRedirect(next)
	else:
		topic_form = TopicAddForm()
		
	next = request.GET.get('next', reverse('fileslibrary:home'))
	context = {'form':topic_form, 'next': next}
	return render(request, 'fileslibrary/topic_add_form.html', context)

fileslibrary/templates/fileslibrary/file_add_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="pt-2">
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form | crispy }}
	<input type="hidden" name="next" value="{{next}}">

	<div class="form-groupe d-flex justify-content-center">
		<button class="btn btn-outline-success m-2" type="submit">Применить</button>
		<a class="btn btn-outline-danger m-2" href="{{next}}">Отмена</a>
	</div>
</form>
</div>
{% endblock %}

fileslibrary/templates/fileslibrary/file_edit_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="pt-2">
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form | crispy }}
	<input type="hidden" name="next" value="{{next}}">

	<div class="form-groupe d-flex justify-content-center">
		<button class="btn btn-outline-success m-2" type="submit">Применить</button>
		<a class="btn btn-outline-danger m-2" href="{{next}}">Отмена</a>
	</div>
</form>
</div>
{% endblock %}

fileslibrary/templates/fileslibrary/files_list.html
{% extends 'base.html' %}
{% load fileslibrary_extras %}


{% block content %}

	{% if contents %}
		{% for section in contents %}
		<div class="my-3">
			<h2 class="w3-large w3-light-grey p-1 px-2">{{section.topic}}</h2>
			<ul style="padding-left: 0px; list-style-type: none;" class="w3-ul">
				{% for file in section.files %}
					<li class="p-1">
						<div class="d-flex">
							{{ file | file_icon }}
							<a href="{{file|file_dispaly_url:request}}" style="text-decoration: none" class="align-self-center">{{file.file_name}}</a>
							
							<span class="ml-auto"></span>
							{% if file.description %}
								<button class="btn-toggle-help-collapse fas fa-question btn btn-outline-info btn-sm ml-2" data-toggle="collapse" data-target="#id_help_collapse_item_{{ forloop.parentloop.counter }}{{ forloop.counter }}" title='Подробней'></button>
							{% endif %}
							<a class="fas fa-download btn btn-outline-info btn-sm ml-2" title='Загрузить' href="{{ file.upload.url }}" download></a>
							<button class="fas fa-share-alt btn btn-outline-info btn-sm ml-2" onclick="copyLink('{{ request.scheme }}://{{ request.get_host }}{{ file.upload.url }}')" title='Копировать ссылку'></button>
							{% if perms.pages.change_page %}
								<a href="{% url 'fileslibrary:edit_file' file.id %}?next={{request.path}}" class="fas fa-pencil-alt btn btn-outline-primary btn-sm ml-4" title='Редактировать'></a>
								<a href="{% url 'fileslibrary:delete_file' file.id %}?next={{request.path}}" class="fas fa-trash-alt btn btn-outline-danger btn-sm ml-2" title='Удалить документ'></a>
							{% endif %}
						</div>
						{% if file.description %}
							<div class="help-collapse collapse" id="id_help_collapse_item_{{ forloop.parentloop.counter }}{{ forloop.counter }}">
								<p class="alert alert-light m-0 my-1 p-1 px-3">{{file.description}}</p>
							</div>
						{% endif %}
					</li>
				{% endfor %}
			</ul>
		</div>
		{% endfor %}

		{% if perms.pages.change_page %}
		<div class="d-flex justify-content-end my-4">
			<a class="btn btn-outline-primary ml-4" href="{% url 'fileslibrary:add_topic' %}?next={{request.path}}">Создать раздел</a>
			<a class="btn btn-outline-primary ml-4" href="{% url 'fileslibrary:add_file' %}?next={{request.path}}">Добавить документ</a>
		</div>
		{% endif %}

	{% else %}
		<p class="pt-4">
			<span class="text-dark py-2">В данном разделе пока еще нет документов.</span>
			{% if perms.pages.change_page %}
				<a class="btn btn-outline-primary ml-4" href="{% url 'fileslibrary:add_topic' %}?next={{request.path}}">Создать раздел</a>
				<a class="btn btn-outline-primary ml-4" href="{% url 'fileslibrary:add_file' %}?next={{request.path}}">Добавить документ</a>
			{% endif %}	
		</p>
		<hr>
	{% endif %}

	<script>
		jQuery('button.btn-toggle-help-collapse').click( function(e) {
		    jQuery('.help-collapse.collapse').collapse('hide');
		});
	</script>

{% endblock %}

fileslibrary/templates/fileslibrary/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="p-3">
		<div class="row">
		<div class="col-md-4 px-2">
			<div class="card hover-card w3-hover-border-blue p-3 pt-3 h-100 w3-pale-green" style="min-height: 210px;">
				<a href="http://wiki.kharkov.owen/index.php/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D1%8B" style="text-decoration: none" class="d-flex justify-content-center">
					<div class="d-flex flex-column">
						<img class="align-self-center" style="width: 130px; height: 130px;" src="{% static 'img/web.png' %}">
						<b><p class="text-secondary text-center p-2 mb-0 hover-card-header">Информационные ресурсы</p></b>
					</div>
				</a>
				<hr class="m-0">
				<div class="py-3 text-dark">
					<p class="mb-2">В данном разделе собраны все информационные ресурсы компании ОВЕН.</p>
					<p class="mb-2">Здесь вы найдете ссылки на SVN, Redmine, Ссылки на страницы компании в различных социальных сеьях и многое другое.</p>
				</div>
				<div class="d-flex h-100">
					<a href="http://wiki.kharkov.owen/index.php/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D1%8B"  class="btn btn-primary btn-sm align-self-end ml-auto">Подробней</a>
				</div>
			</div>
		</div>

		<div class="col-md-4 px-2">
			<div class="card hover-card w3-hover-border-blue p-3 pt-3 h-100 w3-pale-blue" style="min-height: 210px;">
				<a href="{% url 'fileslibrary:regulatory_documents' %}" style="text-decoration: none" class="d-flex justify-content-center">
					<div class="d-flex flex-column">
						<img class="align-self-center" style="width: 130px; height: 130px;" src="{% static 'img/standard.png' %}">
						<b><p class="text-secondary text-center p-2 mb-0 hover-card-header">Нормативная документация</p></b>
					</div>
				</a>
				<hr class="m-0">
				<div class="py-3 text-dark">
					<p class="mb-2">В данном разделе собраны нормативные документы, которыми должен руководствовоться каждый инженер.</p>
					<p class="mb-2">Здесь вы найдете Государственные стандарты (ГОСТы), Международные стандарты (ISO), Отраслевые стандарты и многое другое.</p>
				</div>
				<div class="d-flex h-100">
					<a href="{% url 'fileslibrary:regulatory_documents' %}"  class="btn btn-primary btn-sm align-self-end ml-auto">Подробней</a>
				</div>	
			</div>
		</div>

		<div class="col-md-4 px-2">
			<div class="card hover-card w3-hover-border-blue p-3 pt-3 h-100 w3-pale-yellow" style="min-height: 210px;">
				<a href="{% url 'fileslibrary:articles' %}" style="text-decoration: none" class="d-flex justify-content-center">
					<div class="d-flex flex-column">
						<img class="align-self-center" style="width: 130px; height: 130px;" src="{% static 'img/books.png' %}">
						<b><p class="text-secondary text-center p-2 mb-0 hover-card-header">Литература</p></b>
					</div>
				</a>
				<hr class="m-0">
				<div class="py-3 text-dark">
					<p class="mb-2">В данном разделе собраны книги, статьи, журналы и другая полезная профессиональная литература.</p>
				</div>
				<div class="d-flex h-100">
					<a href="{% url 'fileslibrary:articles' %}"  class="btn btn-primary btn-sm align-self-end ml-auto">Подробней</a>
				</div>			
			</div>
		</div>
		</div>
	</div>

{% endblock %}

fileslibrary/templates/fileslibrary/topic_add_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="pt-2">
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form | crispy }}
	<input type="hidden" name="next" value="{{next}}">

	<div class="form-groupe d-flex justify-content-center">
		<button class="btn btn-outline-success m-2" type="submit">Применить</button>
		<a class="btn btn-outline-danger m-2" href="{{next}}">Отмена</a>
	</div>
</form>
</div>
{% endblock %}